apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "perses.fullname" . }}
  labels:
    {{- include "perses.labels" . | nindent 4 }}
    app.kubernetes.io/component: configuration
  {{- with .Values.config.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  config.yaml: |-
    {{ $config := unset .Values.config "annotations" }}
    {{- with $config }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
