{{- if .Values.serviceMonitor.selfMonitor -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "perses.fullname" . }}
  labels:
    {{- include "perses.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "perses.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace}}
  endpoints:
    - port: {{ .Values.service.portName }}
      interval: {{ .Values.serviceMonitor.interval }}
      path: {{ .Values.config.api_prefix }}/metrics
{{- end -}}